FROM sonarqube:7.9.1-community

# Install Java JDK 11
RUN mkdir -p /usr/lib/jvm && \
    cd /usr/lib/jvm && \
    wget https://download.bell-sw.com/java/11.0.12+8/bellsoft-jdk11.0.12+8-linux-amd64.tar.gz && \
    tar -zxvf bellsoft-jdk11.0.12+8-linux-amd64.tar.gz && \
    rm bellsoft-jdk11.0.12+8-linux-amd64.tar.gz

# Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/bellsoft-jdk11.0.12+8-linux-amd64
ENV PATH $JAVA_HOME/bin:$PATH

# Copy MySQL connector JAR from the local directory into the container
COPY mysql-connector-java-8.0.28.jar /opt/sonarqube/extensions/plugins/

# Set up SonarQube properties to connect to MySQL
RUN sed -i '/^#sonar.jdbc.username/ s/^#//' /opt/sonarqube/conf/sonar.properties && \
    sed -i '/^#sonar.jdbc.password/ s/^#//' /opt/sonarqube/conf/sonar.properties && \
    sed -i '/^#sonar.jdbc.url/ s/^#//' /opt/sonarqube/conf/sonar.properties && \
    sed -i 's/^sonar.jdbc.username=.*/sonar.jdbc.username=sonarqube/' /opt/sonarqube/conf/sonar.properties && \
    sed -i 's/^sonar.jdbc.password=.*/sonar.jdbc.password=Redhat@123/' /opt/sonarqube/conf/sonar.properties && \
    sed -i 's/^sonar.jdbc.url=.*/sonar.jdbc.url=jdbc:mysql:\/\/mysql:3306\/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance/' /opt/sonarqube/conf/sonar.properties

# Start SonarQube
CMD ["./bin/run.sh"]
